Support rpm-based distributions

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,33 +3,47 @@ name: Test
 on:
   workflow_call:
 
+env:
+  IMAGE_DEBIAN_OLDEST: 'debian:oldstable'
+  IMAGE_DEBIAN_STABLE: 'debian:stable'
+  IMAGE_DEBIAN_LATEST: 'debian:testing'
+  IMAGE_DEBIAN_SLIM_OLDEST: 'debian:oldstable-slim'
+  IMAGE_DEBIAN_SLIM_STABLE: 'debian:stable-slim'
+  IMAGE_DEBIAN_SLIM_LATEST: 'debian:testing-slim'
+  IMAGE_UBUNTU_OLDEST: 'ubuntu:focal' # needs manual maintenance on April 2025 (https://ubuntu.com/about/release-cycle)
+  IMAGE_UBUNTU_STABLE: 'ubuntu:latest'
+  IMAGE_UBUNTU_LATEST: 'ubuntu:rolling'
+  IMAGE_CENTOS_OLDEST: '' # CentOS is EOL
+  IMAGE_CENTOS_STABLE: '' # CentOS is EOL
+  IMAGE_CENTOS_LATEST: 'centos:latest'
+  IMAGE_FEDORA_OLDEST: 'fedora:40' # needs manual maintenance on June 2025 (https://docs.fedoraproject.org/en-US/releases/lifecycle/)
+  IMAGE_FEDORA_STABLE: 'fedora:41' # needs manual maintenance on June 2025 (https://docs.fedoraproject.org/en-US/releases/lifecycle/)
+  IMAGE_FEDORA_LATEST: 'fedora:latest'
+  IMAGE_RHEL_OLDEST: 'redhat/ubi8:latest' # needs manual maintenance
+  IMAGE_RHEL_STABLE: 'redhat/ubi9:latest' # needs manual maintenance
+  IMAGE_RHEL_LATEST: 'redhat/ubi9:latest' # needs manual maintenance
+  IMAGE_OPENSUSE_OLDEST: 'opensuse/leap:15.5' # needs manual maintenance on January 2025 (https://endoflife.date/opensuse)
+  IMAGE_OPENSUSE_STABLE: 'opensuse/leap:latest'
+  IMAGE_OPENSUSE_LATEST: 'opensuse/tumbleweed:latest'
+
 jobs:
-  _build:
+  build:
     uses: ./.github/workflows/build.yaml
 
-  install:
-    needs: _build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/download-artifact@v4
-        with:
-          name: package.deb
-      - run: sudo apt-get -y install ./package.deb
-      - run: sudo apt-get -y remove opentelemetry-shell
-
   smoke:
-    needs: install
+    needs: build
     runs-on: ubuntu-latest
     timeout-minutes: 20
     steps:
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - run: sudo -E apt-get -y install ./package.deb
       - run: bash -c "cd tests && bash run_tests.sh bash"
+      - run: sudo apt-get -y remove opentelemetry-shell
 
-  upgrade-prepare:
+  prepare-upgrade:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.dynamic-matrix.outputs.matrix }}
@@ -45,11 +59,11 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
 
   upgrade:
-    needs: [upgrade-prepare, smoke]
+    needs: [prepare-upgrade, smoke]
     runs-on: ubuntu-latest
     timeout-minutes: 15
     strategy:
-      matrix: ${{ fromJSON(needs.upgrade-prepare.outputs.matrix) }}
+      matrix: ${{ fromJSON(needs.prepare-upgrade.outputs.matrix) }}
     steps:
       - run: |
           curl --no-progress-meter --fail --retry 16 --retry-all-errors --header "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/"$GITHUB_REPOSITORY"/releases/tags/${{ matrix.tag_name }} | jq -r '.assets[].browser_download_url' | xargs wget --header "Authorization: Bearer $GITHUB_TOKEN"
@@ -58,20 +72,55 @@ jobs:
       - run: sudo apt-get -y install ./*.deb
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - run: sudo apt-get -y install ./package.deb
 
+  prepare-images:
+    runs-on: ubuntu-latest
+    outputs:
+      images: ${{ steps.dynamic.outputs.images }}
+      images_upgradeable: ${{ steps.dynamic.outputs.images_upgradeable }}
+    steps:
+      - uses: actions/checkout@v4
+      - run: |
+          min_version="$(cat src/DEBIAN/control | grep '^Depends:' | tr ',' '\n' | grep -F -- 'python3 (>=' | cut -d '(' -f 2- | cut -d ')' -f 1 | cut -d ' ' -f 2 | cut -d . -f 2)"
+          printenv | grep '^IMAGE_' | while read -r kvp; do
+            key="$(echo "$kvp" | cut -sd '=' -f 1 | tr '[:upper:]' '[:lower:]')"
+            value="$(echo "$kvp" | cut -sd '=' -f 2)"
+            if [ -z "$value" ]; then continue; fi
+            echo '((apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install python3) || dnf -y install python3 || yum -y install python3 || zypper --non-interactive install python3) > /dev/null && python3 --version' \
+              | sudo docker run --rm --network=host -i "$value" \
+              | cut -d ' ' -f 2 | cut -d . -f 2 | while read -r version; do [ "$version" -ge "$min_version" ] && echo "{\"image\":\"$value\",\"os\":\"$(echo "$key" | cut -d _ -f 2)\",\"type\":\"$(echo "$key" | cut -d _ -f 3)\"}" || true; done
+          done | jq -s > images.json
+          [ "$(cat images.json | jq -r '.[].image' | wc -l)" -ge 5 ] # double check that we dont fail everywhere and then run no tests at all
+          cat images.json | jq '.[]'                                                       | jq .image | sort -u | jq -s -r tostring | xargs -0 -I {} echo 'images={}' >> "$GITHUB_OUTPUT"
+          cat images.json | jq '.[] | select(.type != "latest") | select(.os == "ubuntu")' | jq .image | sort -u | jq -s -r tostring | xargs -0 -I {} echo 'images_upgradeable={}' >> "$GITHUB_OUTPUT"
+        id: dynamic
+
+  prepare-shells:
+    runs-on: ubuntu-latest
+    outputs:
+      shells: ${{ steps.dynamic.outputs.shells }}
+    steps:
+      - uses: actions/checkout@v4
+      - run: |
+          {
+            echo sh
+            cat src/DEBIAN/control | grep '^Enhances: ' | tr ' ' '\n' | tr ',' '\n' | grep -v -F 'Enhances:' | grep -v '^$'
+          } | sort -u | while read -r shell; do echo "\"$shell\""; done | jq -s -r tostring | xargs -0 -I {} echo 'shells={}' >> "$GITHUB_OUTPUT"
+        id: dynamic
+
   system-upgrade:
-    needs: [smoke]
+    needs: [ prepare-images, smoke ]
     runs-on: ubuntu-latest
     timeout-minutes: 15
     strategy:
       matrix:
-        image: ['ubuntu:focal', 'ubuntu:latest', 'ubuntu:rolling']
+        image: ${{ fromJSON(needs.prepare-images.outputs.images_upgradeable) }}
     steps:
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - run: |
           echo '
             apt-get update
@@ -96,43 +145,73 @@ jobs:
             apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade && apt-get -y autoremove && apt-get -y autoclean
           ' | sudo docker run -v $(pwd)/package.deb:/root/package.deb --rm --network=host -i --entrypoint=/bin/sh ${{ matrix.image }} -e
 
+  prepare-dependency:
+    runs-on: ubuntu-latest
+    outputs:
+      dependencies: ${{ steps.dynamic.outputs.dependencies }}
+    steps:
+      - uses: actions/checkout@v4
+      - run: cat src/DEBIAN/triggers | cut -sd ' ' -f 2- | rev | cut -sd / -f 1 | rev | grep -v '^$' | grep -v '^python3$' | sort -u | while read -r dependency; do echo "\"$dependency\""; done | jq -s -r tostring | xargs -0 -I {} echo 'dependencies={}' >> "$GITHUB_OUTPUT"
+        id: dynamic
+
   dependency:
-    needs: [smoke]
+    needs: [ prepare-dependency, prepare-images, smoke ]
     runs-on: ubuntu-latest
     timeout-minutes: 15
     strategy:
       matrix:
-        image: ['debian:oldstable', 'debian:stable', 'debian:testing', 'debian:oldstable-slim', 'debian:stable-slim', 'debian:testing-slim', 'ubuntu:focal', 'ubuntu:latest', 'ubuntu:rolling']
-        dependency: ['npm', 'gcc']
+        image: ${{ fromJSON(needs.prepare-images.outputs.images) }}
+        dependency: ${{ fromJSON(needs.prepare-dependency.outputs.dependencies) }}
     steps:
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - run: |
-          {
-            echo 'apt-get update'
-            echo 'apt-get -y remove ${{ matrix.dependency }}'
-            echo 'DEBIAN_FRONTEND=noninteractive apt-get -y install /root/package.deb'
-            echo 'DEBIAN_FRONTEND=noninteractive apt-get -y install ${{ matrix.dependency }}'
-            echo 'apt-get -y remove ${{ matrix.dependency }}'
-          } | sudo docker run -v $(pwd)/package.deb:/root/package.deb --rm --network=host -i --entrypoint=/bin/sh ${{ matrix.image }} -e
+          echo '
+            if type apt-get; then
+              apt-get update
+              apt-get -y remove ${{ matrix.dependency }}
+              DEBIAN_FRONTEND=noninteractive apt-get -y install /root/package.deb
+              DEBIAN_FRONTEND=noninteractive apt-get -y install ${{ matrix.dependency }}
+              apt-get -y remove ${{ matrix.dependency }}
+            elif type dnf; then
+              dnf -y upgrade --refresh
+              dnf -y remove ${{ matrix.dependency }}
+              dnf -y install /root/package.rpm
+              dnf -y install ${{ matrix.dependency }}
+              dnf -y remove ${{ matrix.dependency }}
+            elif type yum; then
+              yum -y update
+              yum -y remove ${{ matrix.dependency }}
+              yum -y install /root/package.rpm
+              yum -y install ${{ matrix.dependency }}
+              yum -y remove ${{ matrix.dependency }}
+            elif type zypper; then
+              zypper --non-interactive remove ${{ matrix.dependency }} || true
+              zypper --non-interactive install --allow-unsigned-rpm /root/package.rpm
+              zypper --non-interactive install ${{ matrix.dependency }}
+              zypper --non-interactive remove ${{ matrix.dependency }}
+            else
+              exit 1
+            fi
+          ' | sudo docker run -v $(pwd)/package.deb:/root/package.deb -v $(pwd)/package.rpm:/root/package.rpm --rm --network=host -i --entrypoint=/bin/sh ${{ matrix.image }} -e
 
   os-shell:
-    needs: smoke
+    needs: [ prepare-images, prepare-shells, smoke ]
     runs-on: ubuntu-latest
     timeout-minutes: 60
     strategy:
       matrix:
-        os: ['debian:oldstable', 'debian:stable', 'debian:testing', 'debian:oldstable-slim', 'debian:stable-slim', 'debian:testing-slim', 'ubuntu:focal', 'ubuntu:latest', 'ubuntu:rolling']
+        os: ${{ fromJSON(needs.prepare-images.outputs.images) }}
         update: ['FALSE', 'TRUE']
-        shell: [sh, dash, bash, busybox]
-      fail-fast: true
+        shell: ${{ fromJSON(needs.prepare-shells.outputs.shells) }}
+      fail-fast: false
     steps:
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
-      - run: mv ./package.deb tests
+          name: packages
+      - run: mv ./package.* tests
       - run: bash -c 'cd tests && bash run_tests_containerized.sh "$OS" "$UPDATE" "$SHELL"'
         env:
           OS: ${{ matrix.os }}
@@ -148,7 +227,7 @@ jobs:
       - run: printenv | grep '^GITHUB_'
       - uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - run: sudo -E apt-get install ./package.deb
       - uses: actions/checkout@v4
       - uses: ./actions/instrument/job
@@ -164,7 +243,7 @@ jobs:
           [ -n "$TRACEPARENT" ]
       - uses: actions/download-artifact@v4 # check if node action works
         with:
-          name: package.deb
+          name: packages
       - uses: actions/hello-world-docker-action@main # check if docker action works
       - uses: actions/first-interaction@v1 # node action with - in env vars
         with:
@@ -190,7 +269,7 @@ jobs:
            update=TRUE
            shell=bash
 
-  performance-prepare:
+  prepare-performance:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.dynamic-matrix.outputs.matrix }}
@@ -202,16 +281,16 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
   
   performance:
-    needs: [performance-prepare, smoke]
+    needs: [prepare-performance, smoke]
     runs-on: ubuntu-latest
     timeout-minutes: 15
     strategy: 
-      matrix: ${{ fromJSON(needs.performance-prepare.outputs.matrix) }}
+      matrix: ${{ fromJSON(needs.prepare-performance.outputs.matrix) }}
     steps:
       - if: matrix.tag_name == '~local'
         uses: actions/download-artifact@v4
         with:
-          name: package.deb
+          name: packages
       - if: matrix.tag_name != '~local'
         run: |
           curl --no-progress-meter --fail --retry 16 --retry-all-errors --header "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/"$GITHUB_REPOSITORY"/releases | jq -r '.[] | select(.tag_name == "${{ matrix.tag_name }}") | .assets[].browser_download_url' | grep '.deb$' | xargs wget --header "Authorization: Bearer $GITHUB_TOKEN"
@@ -234,7 +313,7 @@ jobs:
           retention-days: 1
 
   join:
-    needs: [install, upgrade, system-upgrade, dependency, os-shell, action, performance]
+    needs: [upgrade, system-upgrade, dependency, os-shell, action, performance]
     runs-on: ubuntu-latest
     outputs:
       success: ${{ steps.tests.outputs.success }}
